services:
  summit-dev-postgres:
    container_name: summit-dev-postgres
    image: postgres:16
    restart: always

    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=maidensix
      - POSTGRES_DB=summit_dev
      - POSTGRES_PASSWORD=M41d3nsix00
      - TZ=America/Sao_Paulo

    volumes:
      - pgdata:/var/lib/postgresql/data

  # authguard:
  #   container_name: auth-guard
  #   image: italorayone/auth-guard:dev
  #   restart: always

  #   depends_on:
  #     - summit-dev-postgres

  #   ports:
  #     - 4004:4004

  #   environment:
  #     NODE_ENV: production

volumes:
  pgdata:
